name: {{cookiecutter.project_name.lower().replace(' ', '_')}}
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - numpy
  - nbconvert
  - nbformat
  - pip
  - pandas
  - pytest
  - pytest-cookies
  - pytest-cov
  - pytest-remotedata==0.3.2  # https://github.com/pytest-dev/pytest/issues/4608#issuecomment-624438127
  - pip:
    - fastapi
    - flake8
    - m2r
    - pyjstat
    - sphinx
    - uvicorn
